"""empty message

Revision ID: 058d0922aeb7
Revises: 2307b8c2200d
Create Date: 2024-01-18 11:44:45.009527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058d0922aeb7'
down_revision = '2307b8c2200d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
