"""change relation from score to exam, to be score to material

Revision ID: 46cb5805c9ec
Revises: 2ce1b6c4965a
Create Date: 2024-02-15 10:27:17.661954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46cb5805c9ec'
down_revision = '2ce1b6c4965a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_id', sa.BigInteger(), nullable=True))
        batch_op.drop_constraint('score_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'material', ['material_id'], ['id'])
        batch_op.drop_column('exam_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('score_ibfk_1', 'exam', ['exam_id'], ['id'])
        batch_op.drop_column('material_id')

    # ### end Alembic commands ###
