"""adding answer model

Revision ID: 66502c5e114e
Revises: 4f18b225d387
Create Date: 2024-02-09 20:13:21.878785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66502c5e114e'
down_revision = '4f18b225d387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('answer', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    # ### end Alembic commands ###
