"""empty message

Revision ID: 6aade0162403
Revises: 
Create Date: 2024-02-16 19:15:23.499209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6aade0162403'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.String(length=250), nullable=False),
    sa.Column('question_number', sa.String(length=100), nullable=False),
    sa.Column('correct_option', sa.String(length=250), nullable=False),
    sa.Column('option_a', sa.String(length=250), nullable=False),
    sa.Column('option_b', sa.String(length=250), nullable=False),
    sa.Column('option_c', sa.String(length=250), nullable=False),
    sa.Column('option_d', sa.String(length=250), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('exam_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('answer', sa.String(length=250), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=250), nullable=False))
        batch_op.drop_column('option_c')
        batch_op.drop_column('option_d')
        batch_op.drop_column('option_b')
        batch_op.drop_column('option_a')
        batch_op.drop_column('question')
        batch_op.drop_column('correct_option')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_option', mysql.VARCHAR(length=250), nullable=False))
        batch_op.add_column(sa.Column('question', mysql.VARCHAR(length=250), nullable=False))
        batch_op.add_column(sa.Column('option_a', mysql.VARCHAR(length=250), nullable=False))
        batch_op.add_column(sa.Column('option_b', mysql.VARCHAR(length=250), nullable=False))
        batch_op.add_column(sa.Column('option_d', mysql.VARCHAR(length=250), nullable=False))
        batch_op.add_column(sa.Column('option_c', mysql.VARCHAR(length=250), nullable=False))
        batch_op.drop_column('title')

    op.drop_table('answer')
    op.drop_table('question')
    # ### end Alembic commands ###
