"""empty message

Revision ID: 83f8e4716933
Revises: cc618b7d10c7
Create Date: 2024-01-11 10:50:58.424961

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "83f8e4716933"
down_revision = "cc618b7d10c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exam",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("material_id", sa.BigInteger(), nullable=True),
        sa.Column("question", sa.String(length=250), nullable=False),
        sa.Column("created_by", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "score",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("score", sa.FLOAT(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("exam_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exam.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("score")
    op.drop_table("exam")
    # ### end Alembic commands ###
