"""empty message

Revision ID: 8774175aa2ca
Revises: c8494f1f3538
Create Date: 2024-01-18 11:30:14.115977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8774175aa2ca'
down_revision = 'c8494f1f3538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.BigInteger(), nullable=False))
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
