"""empty message

Revision ID: 8b63a112c9f8
Revises: da2ef78b6ac5
Create Date: 2024-02-17 11:21:04.023196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b63a112c9f8'
down_revision = 'da2ef78b6ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dob')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
