"""empty message

Revision ID: b43b8e9703f1
Revises: dce655d4cc3e
Create Date: 2024-02-12 22:43:34.619915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b43b8e9703f1'
down_revision = 'dce655d4cc3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_reply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply', sa.Text(), nullable=False))
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_reply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', mysql.TEXT(), nullable=False))
        batch_op.drop_column('reply')

    # ### end Alembic commands ###
