"""empty message

Revision ID: c219e406d9fe
Revises: 7a7001d40e5a
Create Date: 2024-01-18 11:10:19.392154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c219e406d9fe'
down_revision = '7a7001d40e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_id', sa.BigInteger(), nullable=False))
        batch_op.create_foreign_key(None, 'material', ['material_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('material_id')

    # ### end Alembic commands ###
