"""empty message

Revision ID: da2ef78b6ac5
Revises: a0e12552fd0b
Create Date: 2024-02-16 20:50:35.417274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da2ef78b6ac5'
down_revision = 'a0e12552fd0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_id', sa.BigInteger(), nullable=True))
        batch_op.drop_constraint('score_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exam', ['exam_id'], ['id'])
        batch_op.drop_column('material_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('score_ibfk_3', 'material', ['material_id'], ['id'])
        batch_op.drop_column('exam_id')

    # ### end Alembic commands ###
