"""adding relation between comment and material

Revision ID: dce655d4cc3e
Revises: f76e8881be6b
Create Date: 2024-02-12 22:25:17.399209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce655d4cc3e'
down_revision = 'f76e8881be6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_id', sa.BigInteger(), nullable=False))
        batch_op.create_foreign_key(None, 'material', ['material_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('material_id')

    # ### end Alembic commands ###
